# Generated by Django 2.2.7 on 2020-02-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoryORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('_super_admin', '_super_admin'), ('_school_admin', '_school_admin'), ('_teacher', '_teacher'), ('_student', '_student')], max_length=512)),
            ],
        ),
        migrations.AlterModelManagers(
            name='userorm',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='userorm',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SchoolORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('package', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userorm',
            name='category',
            field=models.ForeignKey(default=1, on_delete=None, to='api.UserCategoryORM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorm',
            name='school',
            field=models.ForeignKey(null=True, on_delete=None, to='api.SchoolORM'),
        ),
    ]
