# Generated by Django 2.2.7 on 2020-02-05 18:54

from django.db import migrations
from api.models.constants import UserCategory


def create_default_user_categories(apps, schema_editor):
    UserCategoryORM = apps.get_model('api', 'UserCategoryORM')

    UserCategoryORM.objects.create(name=UserCategory.SUPER_ADMIN).save()
    UserCategoryORM.objects.create(name=UserCategory.SCHOOL_ADMIN).save()
    UserCategoryORM.objects.create(name=UserCategory.TEACHER).save()
    UserCategoryORM.objects.create(name=UserCategory.STUDENT).save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200205_1853'),
    ]

    operations = [
        migrations.RunPython(create_default_user_categories)
    ]
