# Generated by Django 2.2.7 on 2020-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200205_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolorm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
