# Generated by Django 2.2.7 on 2020-02-07 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200206_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultItemORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FloatField()),
                ('exact', models.FloatField()),
                ('digits', models.TextField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ResultORM')),
            ],
        ),
    ]
