# Generated by Django 2.2.7 on 2020-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userorm_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultitemorm',
            name='answer',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='resultitemorm',
            name='exact',
            field=models.FloatField(null=True),
        ),
    ]
