# Generated by Django 2.2.7 on 2020-02-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200215_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitemorm',
            name='action_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultitemorm',
            name='action_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resultitemorm',
            name='count_digit_minus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultitemorm',
            name='count_digits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultitemorm',
            name='speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='resultitemorm',
            name='digits',
            field=models.TextField(null=True),
        ),
    ]
