# Generated by Django 2.2.7 on 2020-02-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200216_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorm',
            name='start_validity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userorm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
