# Generated by Django 2.2.7 on 2020-03-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200304_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
