# Generated by Django 2.2.7 on 2020-03-10 18:55
from django.db import migrations

from api.models.constants import Game


def create_afterburner_game(apps, schema_editor):
    GameORM = apps.get_model('api', 'GameORM')

    afterburner = Game.AFTERBURNER
    GameORM.objects.create(
        name=afterburner.name,
        code=afterburner.code,
        description=afterburner.description
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_gameorm'),
    ]

    operations = [
        migrations.RunPython(create_afterburner_game)
    ]
