# Generated by Django 2.2.7 on 2020-03-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200310_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultorm',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.GameORM'),
        ),
    ]
