# Generated by Django 2.2.7 on 2020-03-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_resultorm_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitemorm',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
