# Generated by Django 2.2.7 on 2020-03-12 16:36
from api.models.constants import Game
from django.db import migrations


def create_multiply_division_square_cube_game(apps, schema_editor):
    GameORM = apps.get_model('api', 'GameORM')

    GameORM.objects.create(
        code=Game.MULTIPLY_DIVISION_SQUARE_CUBE.code,
        name=Game.MULTIPLY_DIVISION_SQUARE_CUBE.name,
        description=Game.MULTIPLY_DIVISION_SQUARE_CUBE.description
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_resultitemorm_points'),
    ]

    operations = [
        migrations.RunPython(create_multiply_division_square_cube_game)
    ]
