# Generated by Django 2.2.7 on 2020-03-21 16:44
from api.models.constants import Game
from django.db import migrations


def create_count_columns_game(apps, schema):
    GameORM = apps.get_model('api', 'GameORM')

    count_columns = Game.COUNT_COLUMNS
    GameORM.objects.create(
        name=count_columns.name,
        code=count_columns.code,
        description=count_columns.description
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_winnerorm'),
    ]

    operations = [
        migrations.RunPython(create_count_columns_game)
    ]
