# Generated by Django 2.2.7 on 2020-03-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200321_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorm',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
