# Generated by Django 2.2.7 on 2020-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_userorm_active_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTypeORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('item_month_duration', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('is_individual', models.BooleanField(default=False)),
            ],
        ),
    ]
