# Generated by Django 2.2.7 on 2020-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200326_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualStudentProposalORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=512)),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProposalORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=512)),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('school_name', models.CharField(max_length=512)),
            ],
        ),
    ]
