# Generated by Django 2.2.7 on 2020-03-31 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200327_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolorm',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PackageTypeORM'),
        ),
    ]
