# Generated by Django 2.2.7 on 2020-04-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_grouporm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorm',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GroupORM'),
        ),
    ]
