# Generated by Django 2.2.7 on 2020-04-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_userorm_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProposalORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed')], max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.PackageTypeORM')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SchoolORM')),
            ],
        ),
    ]
