# Generated by Django 2.2.7 on 2020-04-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_packageproposalorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageproposalorm',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
