# Generated by Django 2.2.7 on 2020-04-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200428_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageproposalorm',
            name='status',
            field=models.CharField(choices=[('_pending', 'Pending'), ('_canceled', 'Canceled'), ('_rejected', 'Rejected'), ('_confirmed', 'Confirmed')], max_length=100),
        ),
    ]
