# Generated by Django 2.2.7 on 2020-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200429_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageproposalorm',
            options={'ordering': ('-id', 'status')},
        ),
        migrations.AlterField(
            model_name='packageproposalorm',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Canceled'), (3, 'Rejected'), (4, 'Confirmed')], default=1, max_length=100),
        ),
    ]
