# Generated by Django 2.2.7 on 2020-05-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200506_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageproposalorm',
            options={'ordering': ('status', '-id')},
        ),
    ]
