# Generated by Django 2.2.7 on 2020-05-11 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200509_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultArchiveORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_at', models.DateTimeField(auto_now_add=True)),
                ('right_answers', models.PositiveSmallIntegerField()),
                ('total_tasks', models.PositiveSmallIntegerField()),
                ('total_points', models.PositiveSmallIntegerField()),
                ('payload', models.TextField()),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.GameORM')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
