# Generated by Django 2.2.7 on 2020-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200512_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultarchiveorm',
            name='submit_at',
            field=models.DateTimeField(),
        ),
    ]
