# Generated by Django 2.2.7 on 2020-06-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200531_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetypeorm',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
