# Generated by Django 2.2.7 on 2020-10-18 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_packagetypeorm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultarchiveorm',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
